
version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_DB=CrmVeiculosAurovel
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
