version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # ====== SEUS VALORES ======
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_DB=CrmVeiculosAurovel
      - JWT_SECRET=${JWT_SECRET}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:3001
      # ====== CORS ======
      - CORS_ORIGINS=https://orange-bay-05cd3f41e.2.azurestaticapps.net,https://aurovelapicontainers.brazilsouth.cloudapp.azure.com,https://localhost:5173,https://localhost:3000
    expose:
      - "3001"               
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3001/health/ready || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  caddy:
    image: caddy:2
    container_name: caddy-proxy
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
volumes:
  caddy_data:
  caddy_config:
